INSERT INTO companies (
    company_id,
    company_name,
    about_us,
    profile_picture_url,
    logo_picture_url,
    location,
    email,
    buddy_name,
    avatar_id,
    final_quote,
    scen_1_text,
    scen1_answer1,
    scen1_answer2,
    scen1_answer3,
    scen1_reaction1,
    scen1_reaction2,
    scen1_reaction3,
    scen2_text,
    scen2_answer1,
    scen2_answer2,
    scen2_answer3,
    scen2_reaction1,
    scen2_reaction2,
    scen2_reaction3,
    buddy_description
) VALUES (
    1,
    'TechNova Solutions',
    'We build innovative software solutions that empower businesses to grow and adapt in a digital world.',
    'https://example.com/images/profile1.png',
    'https://example.com/images/logo1.png',
    'Bucharest, Romania',
    'contact@technova.com',
    'NovaBuddy',
    1,
    'Innovation starts with curiosity.',
    'You are facing a tight project deadline. What do you do?',
    'Work overtime to finish everything yourself',
    'Ask the team for help and divide tasks',
    'Delay the deadline and inform the client',
    'You show dedication, but risk burnout.',
    'Great teamwork! Efficient and balanced approach.',
    'Honesty is good, but try to manage time better.',
    'A client asks for a feature outside the initial scope. Your response?',
    'رفض immediately',
    'Accept and deliver it for free',
    'Negotiate timeline and cost',
    'You protect scope, but may seem inflexible.',
    'Client is happy, but you may lose resources.',
    'Best approach: balance client needs and business value.',
    'Try out this game.'
);